#
# Welcome to the main settings file for TownyMenu.
#
# For help and support please join my discord https://discord.gg/Sgc6hy9CCS
# Issues and bugs, please report at: https://github.com/cobrex1/TownyMenu/issues
#

# The prefix for messages from the plugin
Prefix: "&b&lTM &7// "

# The Language this plugin's messages will be run in.
# The following translations are available: cs, de, en, es, fr, pt, ru and vi. More will follow!
# Once chosen, please re-boot the server to generate the chosen language file.
# It will then appear in the localization folder.
Locale: "en"

# Whether or not economy is enabled or disabled for towny menu corresponding with it being enabled or disabled for Towny
Economy: "true"

# The symbol used in messages for money
Money_Symbol: "$"

# How many milliseconds should an action take before the lag is logged to console
Log_Lag_Over_Milis: 100

# If using HeadDatabase icons, please use the format hdb-[number] eg hdb-34567
# HeadDtabase icons CANNOT be used as fillers

# For item names please use https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# Item to use to display chunk boarders
Chunk_View: REDSTONE_TORCH

##Get Particle names from: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# Particle to use to display chunk boarders
Chunk_View_Particle: VILLAGER_HAPPY

# Back Button icon for all linked menus
Back_Button:
  Item: OAK_DOOR

# -----Filler Icons-----#

# If you wish the filler to be empty, set the material to AIR
# HDB icons cannot be used for fillers

Filler_Join_Nation_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Nation_Toggle:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0

Filler_Nation_Extra_Info_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0

Filler_Join_Town_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Town_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0

Filler_Town_Toggle:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Town_Perms_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Town_General_Settings_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Economy_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Extra_Info_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0

Filler_Plot_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Plot_Toggle_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Plot_Perms_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0
Filler_Plot_Admin_Menu:
  Item: GRAY_STAINED_GLASS_PANE
  CustomModelData: 0

# -------------------------------------------------------------#

# -----Nation Menu Icons-----#

# Non-nation menu
Find_Nation_Button:
  Item: SUNFLOWER
Create_Nation_Button:
  Item: PLAYER_HEAD

# Nation Menu Icons
Nation_Toggle:
  Item: LEVER
  CustomModelData: 0
Nation_Town_List:
  Item: PLAYER_HEAD
  CustomModelData: 0
Nation_Resident_Menu:
  Item: BOOK
  CustomModelData: 0
Nation_Economy_Menu:
  Item: EMERALD_BLOCK
  CustomModelData: 0
Nation_Settings_Menu:
  Item: ENDER_CHEST
  CustomModelData: 0
Nation_Set_Spawn:
  Item: LAPIS_LAZULI
  CustomModelData: 0
Nation_Invite_Town:
  Item: BELL
  CustomModelData: 0
Nation_Extra_Info:
  Item: ENCHANTED_BOOK
  CustomModelData: 0

# Nation Economy Menu Icons
Nation_Balance:
  Item: GOLD_BLOCK
  CustomModelData: 0
Nation_Deposit:
  Item: CHEST
  CustomModelData: 0
Nation_Withdraw:
  Item: ENDER_CHEST
  CustomModelData: 0
Nation_Set_Tax:
  Item: ARROW
  CustomModelData: 0

# Nation Town Menu
Nation_Town_Kick:
  Item: REDSTONE_BLOCK
  CustomModelData: 0

# Nation Resident Menu Icons
Nation_Resident_Rank:
  Item: IRON_SWORD
  CustomModelData: 0
Nation_Set_King:
  Item: GOLDEN_APPLE
  CustomModelData: 0

# Toggle Nation Settings Icons
Nation_Toggle_Public:
  Item: CHEST
  CustomModelData: 0
Nation_Toggle_Open:
  Item: ACACIA_DOOR
  CustomModelData: 0
Nation_Toggle_Tax_Percentage:
  Item: EMERALD
  CustomModelData: 0

# General Nation Settings Menu:
Set_Nation_Spawn:
  Item: GLOWSTONE
  CustomModelData: 0
Set_Nation_Board:
  Item: OAK_SIGN
  CustomModelData: 0
Set_Nation_Name:
  Item: NAME_TAG
  CustomModelData: 0

# Extra Nation Commands:
Nation_Extra_Commands_1:
  Item: BOOK
  CustomModelData: 0
Nation_Extra_Commands_2:
  Item: BOOKSHELF
  CustomModelData: 0
# -------------------------------------------------------------#

# -----Town Menu Icons-----#

# Non-resident menu
Find_Town: SUNFLOWER
Create_Town: PLAYER_HEAD

# Town Main Menu Icons
Toggle_Menu:
  Item: LEVER
  CustomModelData: 0
Resident_List:
  Item: PLAYER_HEAD
  CustomModelData: 0
Permissions_Menu:
  Item: STONE_AXE
  CustomModelData: 0
Economy_Menu:
  Item: EMERALD_BLOCK
  CustomModelData: 0
Plot_Menu:
  Item: WOODEN_SHOVEL
  CustomModelData: 0
Settings_Menu:
  Item: ENDER_CHEST
  CustomModelData: 0
Invite_Menu:
  Item: BELL
  CustomModelData: 0
Extra_Info:
  Item: ENCHANTED_BOOK
  CustomModelData: 0
Town_Info_Icon:
  Item: NETHER_STAR
  CustomModelData: 0

# Toggle Town Settings Icons
Toggle_Fire:
  Item: CAMPFIRE
  CustomModelData: 0
Toggle_Mobs:
  Item: SHULKER_SPAWN_EGG
  CustomModelData: 0
Toggle_Explosions:
  Item: TNT
  CustomModelData: 0
Toggle_PVP:
  Item: GOLDEN_SWORD
  CustomModelData: 0
Toggle_Public:
  Item: CHEST
  CustomModelData: 0
Toggle_Open:
  Item: ACACIA_DOOR
  CustomModelData: 0
Toggle_Tax_Percentage:
  Item: EMERALD
  CustomModelData: 0

# Resident Menu Icons
Resident_Kick:
  Item: REDSTONE_BLOCK
  CustomModelData: 0
Resident_Title:
  Item: NAME_TAG
  CustomModelData: 0
Resident_Rank:
  Item: IRON_SWORD
  CustomModelData: 0
Resident_Mayor:
  Item: GOLDEN_APPLE
  CustomModelData: 0

# Town Permission Menu Icons
Build:
  Item: BRICKS
  CustomModelData: 0
Break:
  Item: GOLDEN_PICKAXE
  CustomModelData: 0
Item_Use:
  Item: FLINT_AND_STEEL
  CustomModelData: 0
Switch:
  Item: LEVER
  CustomModelData: 0

Resident_Build:
  Item: BELL
  CustomModelData: 0
Resident_Break:
  Item: BELL
  CustomModelData: 0
Resident_Item_Use:
  Item: BELL
  CustomModelData: 0
Resident_Switch:
  Item: BELL
  CustomModelData: 0

Nation_Build:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0
Nation_Break:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0
Nation_Item_Use:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0
Nation_Switch:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0

Ally_Build:
  Item: CARROT
  CustomModelData: 0
Ally_Break:
  Item: CARROT
  CustomModelData: 0
Ally_Item_Use:
  Item: CARROT
  CustomModelData: 0
Ally_Switch:
  Item: CARROT
  CustomModelData: 0

Outsider_Build:
  Item: BONE
  CustomModelData: 0
Outsider_Break:
  Item: BONE
  CustomModelData: 0
Outsider_Item_Use:
  Item: BONE
  CustomModelData: 0
Outsider_Switch:
  Item: BONE
  CustomModelData: 0

Reset_All:
  Item: REDSTONE_BLOCK
  CustomModelData: 0
All_On:
  Item: EMERALD_BLOCK
  CustomModelData: 0

# Economy Menu Icons
Town_Balance:
  Item: EMERALD_BLOCK
  CustomModelData: 0
Deposit:
  Item: CHEST
  CustomModelData: 0
Withdraw:
  Item: ENDER_CHEST
  CustomModelData: 0
Set_Tax:
  Item: ARROW
  CustomModelData: 0

# General Town Settings Menu:
Set_Town_Spawn:
  Item: LAPIS_LAZULI
  CustomModelData: 0
Set_Home_Block:
  Item: GLOWSTONE
  CustomModelData: 0
Set_Town_Board:
  Item: OAK_SIGN
  CustomModelData: 0
Set_Town_Name:
  Item: NAME_TAG
  CustomModelData: 0

# Extra Town Info Menu:
Town_Claim_Info:
  Item: GOLDEN_AXE
  CustomModelData: 0
Extra_Commands:
  Item: BOOKSHELF
  CustomModelData: 0
# -------------------------------------------------------------#

# -----Plot Menu Icons-----#

# Plot Menu Icons
Plot_Toggle_Menu:
  Item: LEVER
  CustomModelData: 0
Plot_Permissions_Menu:
  Item: STONE_AXE
  CustomModelData: 0
Plot_Admin_Menu:
  Item: BELL
  CustomModelData: 0
Plot_Friend_Menu:
  Item: ENDER_CHEST
  CustomModelData: 0

Plot_Toggle_Fire:
  Item: CAMPFIRE
  CustomModelData: 0
Plot_Toggle_Mobs:
  Item: SHULKER_SPAWN_EGG
  CustomModelData: 0
Plot_Toggle_Explosions:
  Item: TNT
  CustomModelData: 0
Plot_Toggle_PVP:
  Item: GOLDEN_SWORD
  CustomModelData: 0

# Plot Permission Menu Icons
Plot_Build:
  Item: BRICKS
  CustomModelData: 0
Plot_Break:
  Item: GOLDEN_PICKAXE
  CustomModelData: 0
Plot_Item_Use:
  Item: FLINT_AND_STEEL
  CustomModelData: 0
Plot_Switch:
  Item: LEVER
  CustomModelData: 0

Plot_Resident_Build:
  Item: BELL
  CustomModelData: 0
Plot_Resident_Break:
  Item: BELL
  CustomModelData: 0
Plot_Resident_Item_Use:
  Item: BELL
  CustomModelData: 0
Plot_Resident_Switch:
  Item: BELL
  CustomModelData: 0

Plot_Nation_Build:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0
Plot_Nation_Break:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0
Plot_Nation_Item_Use:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0
Plot_Nation_Switch:
  Item: CHAINMAIL_CHESTPLATE
  CustomModelData: 0

Plot_Ally_Build:
  Item: CARROT
  CustomModelData: 0
Plot_Ally_Break:
  Item: CARROT
  CustomModelData: 0
Plot_Ally_Item_Use:
  Item: CARROT
  CustomModelData: 0
Plot_Ally_Switch:
  Item: CARROT
  CustomModelData: 0

Plot_Outsider_Build:
  Item: BONE
  CustomModelData: 0
Plot_Outsider_Break:
  Item: BONE
  CustomModelData: 0
Plot_Outsider_Item_Use:
  Item: BONE
  CustomModelData: 0
Plot_Outsider_Switch:
  Item: BONE
  CustomModelData: 0

Plot_Reset_All:
  Item: REDSTONE_BLOCK
  CustomModelData: 0
Plot_All_On:
  Item: EMERALD_BLOCK
  CustomModelData: 0

# Plot Admin Menu Icons
Plot_Admin_For_Sale:
  Item: EMERALD_BLOCK
  CustomModelData: 0
Plot_Admin_Not_For_Sale:
  Item: REDSTONE_BLOCK
  CustomModelData: 0
Plot_Admin_Set_Plot_Type:
  Item: DARK_OAK_DOOR
  CustomModelData: 0
Plot_Admin_Evict_Res:
  Item: DIAMOND_AXE
  CustomModelData: 0


# Do not touch below this line
# ---------------------------------------------------------------
Debug: [ ]
Version: 1